configs:
  caddy-file:
    file: ./Caddyfile
  ofelia-conf:
    file: ./ofelia.conf

networks:
  backend:
    internal: true
  frontend:

secrets:
  service-key:
    file: service/.env.keys
  website-key:
    file: website/.env.keys

services:
  db-init:
    build:
      args:
        - TRANSIT_SYSTEM=wmata
    network_mode: none
    volumes:
      - database:/home/data

  cron:
    command:
      [
        "daemon",
        "--docker",
        "--docker-filter=label=com.docker.compose.project=${COMPOSE_PROJECT_NAME}",
      ]
    depends_on:
      - service
    image: mcuadros/ofelia:0.3
    network_mode: none
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  reverse-proxy:
    configs:
      - source: caddy-file
        target: /etc/caddy/Caddyfile
    depends_on:
      - website
    environment:
      - ACME_CA=${ACME_CA:-https://acme-v02.api.letsencrypt.org/directory}
      - DOMAIN=${DOMAIN:-localhost}
    image: caddy:2.11.4
    networks:
      - backend
      - frontend
    ports:
      - "80:80"
      - "443:443"
      - "443:443/UDP"
    restart: unless-stopped
    volumes:
      - caddy-config:/config
      - caddy-data:/data

  service:
    build: service
    depends_on:
      - db-init
    entrypoint: ["sleep", "infinity"]
    environment:
      - DATABASE=sqlite://data/db.sqlite?mode=ro
      - TIMESTAMP=state/timestamp.txt
    labels:
      ofelia.enabled: true
      ofelia.job-exec.wmata.command: "dotenvx run --env-file=.env.prod --env-keys-file=/run/secrets/service-key -- wmata"
      ofelia.job-exec.wmata.schedule: "@every 15m"
    networks:
      - frontend
    secrets:
      - service-key
    volumes:
      - database:/home/data:ro
      - service-timestamp:/home/state

  website:
    build: website
    command: ["fire-alarm-website"]
    depends_on:
      - db-init
    entrypoint:
      [
        "dotenvx",
        "run",
        "--env-file=.env.prod",
        "--env-keys-file=/run/secrets/website-key",
        "--",
      ]
    environment:
      - DATABASE=sqlite://data/db.sqlite
      - URL=0.0.0.0:8080
    expose:
      - 8080
    networks:
      - backend
    restart: unless-stopped
    secrets:
      - website-key
    volumes:
      - database:/home/data

volumes:
  caddy-config:
  caddy-data:
  database:
  service-timestamp:
