[job-run "wmata"]
command = wmata
entrypoint = dotenvx run --env-file=.env.prod --
environment = DATABASE=sqlite://data/db.sqlite?mode=ro
environment = TIMESTAMP=state/timestamp.txt
image = fire-alarm-service
schedule = @every 15m
volume = fire-alarm_database:/home/data:ro
volume = fire-alarm_service-timestamp:/home/state
volume = /home/ubuntu/fire-alarm/service/.env.keys:/home/.env.keys:ro